### ISSUE TITLE
任务没法注册到注册中心

### ISSUE THREAD

**Issue by 1325075688gw** [fcfangcc/pyxxl#21]
1. 我本地git clone了xxl_job:2.3.0
2. 启动了xxl-job-admin（127.0.0.1:8080）、xxl-job-executor-sample-springboot（127.0.0.1:9999）
3. 然后运行pyxxl项目的app.py，但是在xxl-job-admin（127.0.0.1:8080）没有发现任务被注册上去，可以帮忙解决一下吗，是有什么配置错误了吗

![image](https://user-images.githubusercontent.com/22524268/212520096-070fcd83-6c3a-40a4-85ec-a9b1a73f159b.png)
![image](https://user-images.githubusercontent.com/22524268/212520216-b6173555-9b96-4d1d-8050-a3e4bfe5342d.png)
![image](https://user-images.githubusercontent.com/22524268/212520222-b0caab00-cb56-4f65-9aae-9f59abb73bd8.png)

**Comment by fcfangcc** [comment]
@1325075688gw 是不是pyxxl的executor端口和spring的executor端口重复了，pyxxl默认也是9999端口

ExecutorConfig尝试改下端口试试；
`
executor_port=9000，
`

**Comment by 1325075688gw** [comment]
> 

哈喽，我看了一下你写的Python源码，其实并没有向http://localhost:8080/xxl-job-admin/jobinfo/add这个接口发起调用，也就是你的定时任务只能通过xxl_admin界面手动添加吧
![image](https://user-images.githubusercontent.com/22524268/212584371-d460a340-3db8-410e-8193-a24457253f38.png)
你只是做了这个操作
![image](https://user-images.githubusercontent.com/22524268/212584457-f5155cfa-7cd0-4d3a-811e-849a7d5d8c95.png)

**Comment by fcfangcc** [comment]
是的，xxl-admin restful api 不支持自动添加定时任务

**Comment by 1325075688gw** [comment]
> 

应该可以自动添加任务吧，就像xxl_job_admin界面上添加任务，现在只需要在Python代码里面也调用相同的接口 /jobinfo/add就行了，只是你没实现这个功能

**Comment by 1325075688gw** [comment]
> 是的，xxl-admin restful api 不支持自动添加定时任务 @1325075688gw 只支持注册执行器和执行task，任务需要在界面上手动添加

定时任务一种是定时执行，另外一种是靠事件触发的，比如我web服务add接口收到一个请求后，我想在收到这个请求30分钟后做一件事情，这时候我们就需要在代码触发 /xxl_job_admin/jobinfo/add接口，将执行时间等传过去。

**Comment by 1325075688gw** [comment]
方便加一下微信吗，我有些其他问题请求一下:15023328110

**Comment by fcfangcc** [comment]
那样就是走的界面的http的接口，不是标准流程。他本身提供的执行器标准的restful接口没有这个功能。 [调度中心 RESTful API](https://www.xuxueli.com/xxl-job/#%E5%85%AD%E3%80%81%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83/%E6%89%A7%E8%A1%8C%E5%99%A8%20RESTful%20API)

你说的这个需求的话，应该不是执行器做的。我觉得应该有个单独的py包来调用xxl-job的web接口发起请求比较合理。
