### ISSUE TITLE
如何将执行器的错误和进度返回给调度中心?

### ISSUE THREAD

**Issue by showkeyjar** [fcfangcc/pyxxl#28]
目前的示例和文档仅包含正常情况下的返回

1.如何返回错误？使得调度中心能触发错误重试或故障转移？

2.再有就是执行的进度如何返回？

**Comment by fcfangcc** [comment]
只需要程序raise异常即可  执行器收到异常会回调给调度器报告这次任务执行失败以及原因

**Comment by showkeyjar** [comment]
好的，我试试
