### ISSUE TITLE
和flask集成

### ISSUE THREAD

**Issue by lanxing** [fcfangcc/pyxxl#39]
如何和flask进行集成？
app.run_executor()会起一个web服务器，且是阻塞的，无法和flask进行集成

**Comment by fcfangcc** [comment]
flask是如何启动的，如果是gunicorn启动的请参考  [run-with-gunicorn](https://fcfangcc.github.io/pyxxl/example/#gunicorn-runserver) 

run_with_daemon 会单独起一个进程运行executor

**Comment by timhengc** [comment]
链接失效了，可以更新一下吗
