### ISSUE TITLE
Feature Request: 希望有个关于日志设置的特性

### ISSUE THREAD

**Issue by KunxiSun** [fcfangcc/pyxxl#44]
**问题描述**

日志生成方式是默认以disk的方式，生成日志。日志的名称是"pyxxl-{id}.log"的方式。这样虽然查询的时候会很简便，但是导致了日志目录下很多文件
![image](https://github.com/fcfangcc/pyxxl/assets/57077817/f9c74abd-e4be-4c62-aa38-368e4a21d243)

可不可以有个修改日志记录方式的设置在ExecutorConfig里，只生成一个日志文件，里面记录了所有日志，把id放在日志里，而不是文件名里。

最好还可以修改日志的上限！

**问题详情**

```python
最好可以附上代码
ExecutorConfig(
        loggger = ”normal” | “disk” | "redis"
       ...
)
```

**Comment by fcfangcc** [comment]
这个日志文件会定时清理的。后面我加一下可以配置清理的周期，目前是1小时清理一次， 保存14天的日志……
