### ISSUE TITLE
不支持xxljob 的 gule(shell)模式呀

### ISSUE THREAD

**Issue by xuemingjings** [fcfangcc/pyxxl#45]
**Problem description**

详细描述你的问题

**Steps to reproduce the problem**

```python
最好可以附上代码
```

**Specifications like the version of the project, operating system, or hardware**

* XXL-JOB 版本:
* pyxxl 版本:
* python 版本:
* other more:

**Comment by fcfangcc** [comment]
这个库主要是为了方便注册Python写的逻辑，要用gule(shell)推荐用Java的Executor
