### ISSUE TITLE
可以使用uvicorn来启动吗

### ISSUE THREAD

**Issue by huangyemin** [fcfangcc/pyxxl#46]
**Problem description**

详细描述你的问题

可以使用uvicorn来启动吗

**Specifications like the version of the project, operating system, or hardware**

* XXL-JOB 版本:
* pyxxl 版本:
* python 版本:
* other more:

**Comment by fcfangcc** [comment]
参考 [Flask](https://fcfangcc.github.io/pyxxl/example/#run-with-flask-only-for-develop),但是不建议生产环境这样使用，建议web和pyxxl分开部署
