### ISSUE TITLE
pyxxl这个库有封装对任务进行停止的函数或者方法吗

### ISSUE THREAD

**Issue by zzzjw666** [fcfangcc/pyxxl#47]
**Problem description**

详细描述你的问题
作者您好，现在我遇到一个问题，就是想在代码里面对任务进行停止，但是我看了一下pyxxl的文档，好像没有写对任务停止调用哪个函数或者方法

**Steps to reproduce the problem**

```python
最好可以附上代码
```

**Specifications like the version of the project, operating system, or hardware**

* XXL-JOB 版本: 2.4.0
* pyxxl 版本: 0.3.4
* python 版本: 3.9.18
* other more:

**Comment by zzzjw666** [comment]
就是不想在XXL-JOB-ADMIN界面上点击停止，而是想通过代码动态的去中断任务，pyxxl这个库现在有实现这个功能吗

**Comment by fcfangcc** [comment]
不是很理解你的意思

是指额外有个程序A去调用pyxxl-Executor程序来关闭指定任务？
还是说在pyxxl-Executor程序里面满足某个条件之后关闭指定任务？

**Comment by zzzjw666** [comment]
你也可以理解为你所说的，有个程序A去调用pyxxl-Executor程序来关闭指定任务

**Comment by fcfangcc** [comment]
@zzzjw666 前提是需要知道jobid，可以调pyxxl-Executor http的这个接口 https://github.com/fcfangcc/pyxxl/blob/e40deaa7d7541dcfaa87dc3d2caf8b46a49f4df2/pyxxl/server.py#L66-L70

其他没有相关功能

**Comment by zzzjw666** [comment]
好的，明白~
