### ISSUE TITLE
支持GLUE 模式

### ISSUE THREAD

**Issue by CyanZoy** [fcfangcc/pyxxl#50]
作者大大能否增加一下GLUE的模式，我看注册任务的时候没有指定name就会默认使用func的name
![image](https://github.com/fcfangcc/pyxxl/assets/34015086/7a1c4887-a35a-4072-9ccf-f902a1f18b45)
但是GLUE，xxljob发送过来的数据handler是空的，导致拿不到用户定义的handler
![image](https://github.com/fcfangcc/pyxxl/assets/34015086/4db4d43d-24ef-4913-b2d5-fffa37d4c686)

**Comment by fcfangcc** [comment]
GLUE我的理解就是去执行一个Python脚本？如果是这样，直接把GLUE的源码写入到executor的一个function上不是更好维护么

另外GLUE用Java的executor也可以跑吧，没必要用PYXXL
